# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'PaymentRequest'
        db.create_table('skrill_paymentrequest', (
            ('user', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['auth.User'])),
            ('time', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('test', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('submitted', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('transaction_id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('pay_to_email', self.gf('django.db.models.fields.EmailField')(default='help@bbg-entertainment.com', max_length=50)),
            ('recipient_description', self.gf('django.db.models.fields.CharField')(default='myBrainTraining.com', max_length=30, null=True, blank=True)),
            ('return_url', self.gf('django.db.models.fields.URLField')(default=u'http://example.com/skrill/return/', max_length=240, null=True, blank=True)),
            ('return_url_text', self.gf('django.db.models.fields.CharField')(default='Back to myBrainTraining.com', max_length=35, null=True, blank=True)),
            ('return_url_target', self.gf('django.db.models.fields.SmallIntegerField')(default=1)),
            ('cancel_url', self.gf('django.db.models.fields.URLField')(default=u'http://example.com/skrill/cancel/', max_length=240, null=True, blank=True)),
            ('cancel_url_target', self.gf('django.db.models.fields.SmallIntegerField')(default=1)),
            ('status_url', self.gf('django.db.models.fields.CharField')(default=u'http://example.com/skrill/status_report/', max_length=255, null=True, blank=True)),
            ('status_url2', self.gf('django.db.models.fields.CharField')(default=None, max_length=255, null=True, blank=True)),
            ('new_window_redirect', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('language', self.gf('django.db.models.fields.CharField')(default='EN', max_length=2)),
            ('hide_login', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('confirmation_note', self.gf('django.db.models.fields.CharField')(default=None, max_length=240, null=True, blank=True)),
            ('logo_url', self.gf('django.db.models.fields.URLField')(default=None, max_length=240, null=True, blank=True)),
            ('prepare_only', self.gf('django.db.models.fields.BooleanField')(default=True)),
            ('rid', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('ext_ref_id', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('custom_field_1', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_2', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_3', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_4', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_5', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('pay_from_email', self.gf('django.db.models.fields.EmailField')(max_length=100, null=True, blank=True)),
            ('title', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('firstname', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('lastname', self.gf('django.db.models.fields.CharField')(max_length=50, null=True, blank=True)),
            ('date_of_birth', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('address', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('address2', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('phone_number', self.gf('django.db.models.fields.PositiveIntegerField')(max_length=20, null=True, blank=True)),
            ('postal_code', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('city', self.gf('django.db.models.fields.CharField')(max_length=50, null=True, blank=True)),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=50, null=True, blank=True)),
            ('country', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('amount', self.gf('django.db.models.fields.DecimalField')(max_digits=18, decimal_places=2)),
            ('currency', self.gf('django.db.models.fields.CharField')(default='EUR', max_length=3)),
            ('amount2_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('amount2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=18, decimal_places=2, blank=True)),
            ('amount3_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('amount3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=18, decimal_places=2, blank=True)),
            ('amount4_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('amount4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=18, decimal_places=2, blank=True)),
            ('detail1_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail1_text', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail2_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail2_text', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail3_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail3_text', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail4_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail4_text', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail5_description', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('detail5_text', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
        ))
        db.send_create_signal('skrill', ['PaymentRequest'])

        # Adding model 'StatusReport'
        db.create_table('skrill_statusreport', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('time', self.gf('django.db.models.fields.DateTimeField')(auto_now_add=True, blank=True)),
            ('valid', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('signal_sent', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('pay_to_email', self.gf('django.db.models.fields.EmailField')(default='help@bbg-entertainment.com', max_length=50)),
            ('pay_from_email', self.gf('django.db.models.fields.EmailField')(max_length=50)),
            ('merchant_id', self.gf('django.db.models.fields.PositiveIntegerField')()),
            ('customer_id', self.gf('django.db.models.fields.PositiveIntegerField')(null=True, blank=True)),
            ('payment_request', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['skrill.PaymentRequest'])),
            ('mb_transaction_id', self.gf('django.db.models.fields.PositiveIntegerField')()),
            ('mb_amount', self.gf('django.db.models.fields.DecimalField')(max_digits=18, decimal_places=2)),
            ('mb_currency', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('status', self.gf('django.db.models.fields.IntegerField')()),
            ('failed_reason_code', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('md5sig', self.gf('django.db.models.fields.CharField')(max_length=32)),
            ('sha2sig', self.gf('django.db.models.fields.CharField')(max_length=64, null=True, blank=True)),
            ('amount', self.gf('django.db.models.fields.DecimalField')(max_digits=18, decimal_places=2)),
            ('currency', self.gf('django.db.models.fields.CharField')(max_length=3)),
            ('payment_type', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('custom_field_1', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_2', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_3', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_4', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
            ('custom_field_5', self.gf('django.db.models.fields.CharField')(max_length=240, null=True, blank=True)),
        ))
        db.send_create_signal('skrill', ['StatusReport'])


    def backwards(self, orm):
        # Deleting model 'PaymentRequest'
        db.delete_table('skrill_paymentrequest')

        # Deleting model 'StatusReport'
        db.delete_table('skrill_statusreport')


    models = {
        'auth.group': {
            'Meta': {'object_name': 'Group'},
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        'auth.permission': {
            'Meta': {'ordering': "('content_type__app_label', 'content_type__model', 'codename')", 'unique_together': "(('content_type', 'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['contenttypes.ContentType']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': "orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'skrill.paymentrequest': {
            'Meta': {'ordering': "['time']", 'object_name': 'PaymentRequest'},
            'address': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'address2': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'amount': ('django.db.models.fields.DecimalField', [], {'max_digits': '18', 'decimal_places': '2'}),
            'amount2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '18', 'decimal_places': '2', 'blank': 'True'}),
            'amount2_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'amount3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '18', 'decimal_places': '2', 'blank': 'True'}),
            'amount3_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'amount4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '18', 'decimal_places': '2', 'blank': 'True'}),
            'amount4_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'cancel_url': ('django.db.models.fields.URLField', [], {'default': "u'http://example.com/skrill/cancel/'", 'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'cancel_url_target': ('django.db.models.fields.SmallIntegerField', [], {'default': '1'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'confirmation_note': ('django.db.models.fields.CharField', [], {'default': 'None', 'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'currency': ('django.db.models.fields.CharField', [], {'default': "'EUR'", 'max_length': '3'}),
            'custom_field_1': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_2': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_3': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_4': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_5': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'date_of_birth': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'detail1_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail1_text': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail2_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail2_text': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail3_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail3_text': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail4_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail4_text': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail5_description': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'detail5_text': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'ext_ref_id': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'firstname': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'hide_login': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'language': ('django.db.models.fields.CharField', [], {'default': "'EN'", 'max_length': '2'}),
            'lastname': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'logo_url': ('django.db.models.fields.URLField', [], {'default': 'None', 'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'new_window_redirect': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'pay_from_email': ('django.db.models.fields.EmailField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'pay_to_email': ('django.db.models.fields.EmailField', [], {'default': "'help@bbg-entertainment.com'", 'max_length': '50'}),
            'phone_number': ('django.db.models.fields.PositiveIntegerField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'postal_code': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'prepare_only': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'recipient_description': ('django.db.models.fields.CharField', [], {'default': "'myBrainTraining.com'", 'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'return_url': ('django.db.models.fields.URLField', [], {'default': "u'http://example.com/skrill/return/'", 'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'return_url_target': ('django.db.models.fields.SmallIntegerField', [], {'default': '1'}),
            'return_url_text': ('django.db.models.fields.CharField', [], {'default': "'Back to myBrainTraining.com'", 'max_length': '35', 'null': 'True', 'blank': 'True'}),
            'rid': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'status_url': ('django.db.models.fields.CharField', [], {'default': "u'http://example.com/skrill/status_report/'", 'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'status_url2': ('django.db.models.fields.CharField', [], {'default': 'None', 'max_length': '255', 'null': 'True', 'blank': 'True'}),
            'submitted': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'test': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'time': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'transaction_id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['auth.User']"})
        },
        'skrill.statusreport': {
            'Meta': {'ordering': "['time']", 'object_name': 'StatusReport'},
            'amount': ('django.db.models.fields.DecimalField', [], {'max_digits': '18', 'decimal_places': '2'}),
            'currency': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'custom_field_1': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_2': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_3': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_4': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'custom_field_5': ('django.db.models.fields.CharField', [], {'max_length': '240', 'null': 'True', 'blank': 'True'}),
            'customer_id': ('django.db.models.fields.PositiveIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'failed_reason_code': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mb_amount': ('django.db.models.fields.DecimalField', [], {'max_digits': '18', 'decimal_places': '2'}),
            'mb_currency': ('django.db.models.fields.CharField', [], {'max_length': '3'}),
            'mb_transaction_id': ('django.db.models.fields.PositiveIntegerField', [], {}),
            'md5sig': ('django.db.models.fields.CharField', [], {'max_length': '32'}),
            'merchant_id': ('django.db.models.fields.PositiveIntegerField', [], {}),
            'pay_from_email': ('django.db.models.fields.EmailField', [], {'max_length': '50'}),
            'pay_to_email': ('django.db.models.fields.EmailField', [], {'default': "'help@bbg-entertainment.com'", 'max_length': '50'}),
            'payment_request': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['skrill.PaymentRequest']"}),
            'payment_type': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'sha2sig': ('django.db.models.fields.CharField', [], {'max_length': '64', 'null': 'True', 'blank': 'True'}),
            'signal_sent': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'status': ('django.db.models.fields.IntegerField', [], {}),
            'time': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'valid': ('django.db.models.fields.BooleanField', [], {'default': 'False'})
        }
    }

    complete_apps = ['skrill']